### ISSUE TITLE
'DS' and 'Firebase' not defined...

### ISSUE THREAD

**Issue by jvenator** [tikotzky/ember-cli-emberfire#2]
This seems to no longer be working in ember-cli 0.1.2

```
2014-11-12 16:37 ember[29165] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

adapters/application.js: line 1, col 16, 'DS' is not defined.
adapters/application.js: line 2, col 17, 'Firebase' is not defined.

2 errors
```

Do you have any suggestions?

**Comment by brandonjmckay** [comment]
I'm on Ember CLI 0.1.5, and getting this as well.

This is my adapter.

```
import config from '../config/environment';
import Firebase from 'firebase';
import FirebaseAdapter from 'emberfire/adapters/firebase';

export default FirebaseAdapter.extend({
  firebase: new Firebase(config.firebase)
});
```

**Comment by brandonjmckay** [comment]
@jvenator did you check your import lines? `DS` should be defined because it's stock Ember. 
You would need to do `import DS from 'ember-data';` to get it. But you may not need it _—not sure—_ if you're just going for the FirebaseAdapter like I am.

**Comment by tikotzky** [comment]
@brandonjmckay this addon is deprecated. It was only needed before emberfire supported ember-cli.

Now you should be able to install emberfire directly using ember-cli.

See: https://github.com/firebase/emberfire#installing-emberfire-with-the-ember-cli

**Comment by bj-mcduck** [comment]
@tikotzky thanks. That's likely the cause of my troubles right there.
